services:
  cms:
    image: php:8.2-apache
    container_name: cms
    ports:
      - "7075:80"
    volumes:
      - ../:/var/www/html
    environment:
      PHP_OPCACHE_ENABLE: 0
    restart: unless-stopped
    depends_on:
      - db
    command: >
      bash -c "apt-get update && apt-get install -y libpq-dev && docker-php-ext-install pdo_mysql && a2enmod rewrite && apache2-foreground"
  db:
    image: mysql:8
    container_name: cms_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: cmsdb
      MYSQL_USER: sa
      MYSQL_PASSWORD: Aa@12345
    ports:
      - "3326:3306"
    volumes:
      - db_data:/var/lib/mysql

x-project:
  name: sunoid

volumes:
  db_data: